version: 2

models:

  - name: agg_orders
    description: This model aggregates order-level data

    columns:
      - name: order_date
        description: Date (UTC) of the order
        tests:
          - not_null
      - name: status
        description: Order status
      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: total_amount
        description: Sum of the order amounts
        tests:
          - not_null
